### ISSUE TITLE
Docker image isnt still working

### ISSUE THREAD

**Issue by ghost** [galexrt/docker-sinusbot#42] opened 2018-08-19 22:15 UTC
I updated the image and restartet the sinusbot but i isnt still working :D 
in docker logs is this:

Checking if scripts directory is empty
=> Scripts directory is marked, scripts were already copied. Nothing to do.
-> No /sinusbot/config/config.ini found, not linking.
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.14.3-0e747fd
(C) 2013-2018 Michael Friese. All rights reserved.

2018/08/19 22:13:06 X [MAIN] Starting up fake x-server...
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2018/08/19 22:13:06 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
could not contact update server

It is the same error before and in docker ps it isnt showing up

**Comment by galexrt** [comment] 2018-08-20 13:17
@Scuddix I'm unable to reproduce the error.
Are you sure your server can reach the Sinusbot website as stated in forum posts about this issue?

**Comment by ghost** [comment] 2018-08-26 15:32
I have reinstalled the note twiced but couldnt get to any soloution. I also couldnt reproduce this error on a other server. I think the update server just blocked my IP :D But If you are a nice person and promise to not damage my server i can provide login credentials So you can fix the bug.

**Comment by galexrt** [comment] 2018-08-26 16:03
@Scuddix You have to reach out to the Sinusbot.com admins/makers to ask them for your IP to be unbanned. This is nothing I have in control.

Closing as this is not a problem with the Docker image in this case.

**Closed as completed by galexrt** 2018-08-26 16:03 UTC
