### ISSUE TITLE
Instances do not start: "ERROR |SoundBckndIntf| |libpulse.so.0"

### ISSUE THREAD

**Issue by adroste** [galexrt/docker-sinusbot#32] opened 2018-02-25 22:57 UTC
Updating my container / migrating from "old" image broke my bot:

When trying to start bot-instance, it no longer enters TS-Channel and log shows: 
"|ERROR |SoundBckndIntf| |libpulse.so.0: cannot open shared object file: No such file or directory"

**Comment by galexrt** [comment] 2018-02-26 09:04
@progmem64 Could you post the full logs of the container.

**Comment by adroste** [comment] 2018-02-28 16:56
```
-> Checking if scripts directory is empty
=> Scripts directory is marked, scripts were already copied. Nothing to do.
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
2018/02/28 16:52:21 X [MAIN] Starting up fake x-server...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |  
|___/___|_|\_|\___/|___/___/\___/ |_|  

Version: 0.13.37-9791176
(C) 2013-2017 Michael Friese. All rights reserved.

2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2018/02/28 16:52:21 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
2018/02/28 16:52:21 88838496          INFO   Loading instances
2018/02/28 16:52:21 88838496          INFO   Loading instance://3c3d02ae-6c8a-479a-b887-96079919f653
2018/02/28 16:52:21 88838496 3c3d02ae INFO   Initialization complete
2018/02/28 16:52:21 88838496 3c3d02ae INFO   Last track was 70c5850a-5b4d-439c-bd34-42c16087469d, will auto-play soon
2018/02/28 16:52:21 88838496          INFO   Loading instance://ecef0a2c-ed2f-422f-85c2-287cb034c7c5
2018/02/28 16:52:21 88838496 ecef0a2c INFO   Initialization complete
2018/02/28 16:52:21 [GENERAL/FFMPEG ] INFO   FFmpeg/avcodec v3741798; license: LGPL version 2.1 or later; 81 codecs
2018/02/28 16:52:21 [GENERAL/FFMPEG ] INFO   FFmpeg/avformat v3742052; license: LGPL version 2.1 or later; 143 formats
2018/02/28 16:52:21 [GENERAL/YTDL   ] INFO   youtube-dl checking...
2018/02/28 16:52:22 88838496 3c3d02ae INFO   Auto-Playing last track
2018/02/28 16:52:22 [GENERAL/YTDL   ] INFO   youtube-dl version compatible, support enabled
2018/02/28 16:52:22 [GENERAL/!!!!!!!] NOTICE You may now configure and launch the bots from the webinterface. http://0.0.0.0:8087
2018/02/28 16:52:22 [GENERAL/RADIO  ] INFO   RadioStation data loaded
2018/02/28 16:52:22 [GENERAL/RADIO  ] INFO   Imported radio stations
2018/02/28 16:52:22 [AUDIOPROXY     ] Streaming http://[removed].mp3
2018/02/28 16:52:34 88838496          INFO   LOGIN [admin] OK
2018/02/28 16:52:39 88838496          INFO   LOGIN [admin] OK
2018/02/28 16:52:46 88838496 3c3d02ae WARN   Could not create Chat-Tabletable Chat already exists
2018/02/28 16:52:46 88838496 3c3d02ae WARN   Could not create WhisperReceive-Tabletable WhisperReceive already exists
2018/02/28 16:52:46 88838496 3c3d02ae WARN   Could not create Notifications-Tabletable Notifications already exists
2018/02/28 16:52:46 88838496 3c3d02ae INFO   Starting instance ts3server://[removed]?port=9987&nickname=JukeBox&password=&cid=7&channelpassword=
2018/02/28 16:52:46 X [MAIN] New connection
2018/02/28 16:52:46 X [MAIN] New connection
2018/02/28 16:52:46 X [MAIN] New connection
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |              |   |TeamSpeak 3 Client 3.1.8 (2018-01-22 09:50:07)
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |              |   |SystemInformation: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 Binary: 64bit
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |              |   |Using hardware aes
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |ERROR   |SoundBckndIntf|   |libpulse.so.0: cannot open shared object file: No such file or directory
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |Unable to create an Open GL context.
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |Addons        |   |Checking for addon updates...
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |              |   |successfully downloaded revocation list
2018/02/28 16:52:46 88838496 3c3d02ae INFO   TS |INFO    |Plugins       |   |Loading plugin: libsoundbot_plugin.so
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |              |   |*** Time [MAINWINDOW]: 307
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |              |   |*** Time [INIT]: 307
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |DEVELOP |ClientUI      |   |Notifications init: Soundpack path: /sinusbot/TeamSpeak3-Client-linux_amd64/sound/nosounds
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |Failed to init text to speech engine
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |Qt version: 5.6.1
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |Using configuration location: /sinusbot/data/ts3/88838496-674e-4b88-8c99-5c9b84b11239/3c3d02ae-6c8a-479a-b887-96079919f653/settings.db
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |ts3server: [removed]?port=9987&nickname=JukeBox&password=&cid=7&channelpassword=
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |1  |Connect to server: [removed]
2018/02/28 16:52:47 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |1  |Initiating connection: [removed]:9987
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |INFO    |PreProSpeex   |1  |Speex version: 1.2rc1
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |1  |Connect status: Connecting
2018/02/28 16:52:48 88838496 3c3d02ae INFO   New connection status 1; Error 0
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |INFO    |Bookmarks     |   |Collecting autoconnect bookmarks
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |   |Last update check was: Tue Jan 1 00:00:01 2019
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |INFO    |              |   |Statistics report: Not yet, next report on Fri Mar 2 15:20:32 2018
2018/02/28 16:52:48 88838496 3c3d02ae INFO   TS |DEVELOP |PktHandler    |   |Puzzle solve time: 2
2018/02/28 16:52:53 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |1  |Connect status: Disconnected
2018/02/28 16:52:53 88838496 3c3d02ae INFO   TS |INFO    |ClientUI      |1  |Failed to connect to server, want autoreconnect = 0
2018/02/28 16:52:53 88838496 3c3d02ae INFO   The bot could not connect. This might have several reasons: the server doesn't exist at that address, the server password is wrong, the default channel doesn't exist, the bot has been banned, the server is an illegal installation or the password is wrong , the security level of your identity is too low or the server does not allow the version of the client you are using. See our Wiki / Forums for more help.
2018/02/28 16:52:53 88838496 3c3d02ae INFO   New connection status 0; Error 1797
2018/02/28 16:52:54 88838496 3c3d02ae INFO   TSClient quit.
```

Already tried to connect to a different server, same Error.

**Comment by galexrt** [comment] 2018-02-28 16:58
It says that it is not able to connect to the server `Failed to connect to server, want autoreconnect = 0`.
Did you already try to connect to another TeamSpeak server?

**Comment by adroste** [comment] 2018-03-02 11:28
> Already tried to connect to a different server, same Error.

Yes i did.

**Comment by galexrt** [comment] 2018-03-02 16:23
* What image version are you currently on? For quay.io image `docker images quay.io/galexrt/sinusbot:latest` or Docker Hub `galexrt/sinusbot:latest`. Are you sure you are on the latest image version?
* Are you just starting the container and the TS3 instance doesn't start, or did you also try to start the Ts3 instance using the web interface?
* Have you already checked if Sinusbot can connect to the server from a fresh instance? e.g. `docker run -p 8087:8087 quay.io/galexrt/sinusbot:latest` (without `-v` flags).

**Comment by adroste** [comment] 2018-03-03 16:55
Latest Version using Docker Hub. TS3 instance does not start after starting the container, manual restarting via web-interface also does not fix it. Yes i already tried creating and starting a bot from a fresh instance.

Host System: up-to-date Debian 8.10
Docker: version 17.12.0-ce, build c97c6d6

**Comment by galexrt** [comment] 2018-03-05 09:46
@progmem64 I have just tested it with the following versions and specs and I can start the TS3 client and connect to servers and play music:
Docker: `18.02.0-ce`
Debian: `9.3`
VM had 4GB RAM

Can you try updating Debian and/or Docker to check if the issue persists?

**Comment by adroste** [comment] 2018-03-11 15:42
Updated my whole system:
Debian: 9.4
Docker: 17.12.1-ce, build 7390fc6 (this is the newest stable, 18 is an "Edge" release)

I did not reuse my old containers or inject some existing data. I started (for testing purposes) a fresh teamspeak3 and a fresh sinusbot container. Same problem.

Tested TS3-Server Versions: 3.1.1 & 3.0.12
Used Images: aheil/teamspeak3-server & mbentley/teamspeak

**Comment by Horstexplorer** [comment] 2018-03-20 19:32
The SoundBckndIntf-libpulse.so.0 error may be fixed by adding the package (not sure if its 'libpulse') to the docker, but it doesnt seem to affect the functionality of the bot if libpulse isnt there.
I'm guessing that the problem here is the ts server version or the security level. The bot will only be able to connect to the server if the security level is equal or below 9 cause of their identity.
I tried out aheil/teamspeak3-server on 3.0.x too as I tried to set up the Sinusbot but it didnt worked for me, so I swaped to mbentley/teamspeak. This worked for me, so it may help you too.

**Comment by galexrt** [comment] 2018-03-24 18:48
@Horstexplorer Thank you for looking into this issue!

@progmem64 Could you verify the "fix" @Horstexplorer wrote? I only tested with TeamSpeak 3 servers version >= 3.1.0.
That could be the missing piece why it isn't working for you.

**Comment by galexrt** [comment] 2018-07-03 06:03
Closing as this issue seems to be related to @progmem64 using an old TS3 version from what @Horstexplorer wrote.
Also I can't reproduce with an up-to-date TS3 server that Sinusbot TS3 client can't connect.

**Closed as completed by galexrt** 2018-07-03 06:03 UTC

**Comment by RealRunSpace** [comment] 2018-07-06 17:26
how can we change the ts3 version so? I have the same problem, discord seems fine

**Comment by RealRunSpace** [comment] 2018-07-06 17:27
TS3 version 3.1.9 (Is a fresh server installation with only 2 instances)

**Comment by RealRunSpace** [comment] 2018-07-06 17:28
```2018/07/06 17:23:04 903988b8 f5cc50a5 INFO   BOT-CONFIG [admin] CHAN CHANPW ANNOUNCE DESCRIPTION ANNOUNCESTR TTSURL CC OK
2018/07/06 17:23:06 903988b8 f5cc50a5 WARN   Could not create Chat-Tabletable Chat already exists
2018/07/06 17:23:06 903988b8 f5cc50a5 WARN   Could not create WhisperReceive-Tabletable WhisperReceive already exists
2018/07/06 17:23:06 903988b8 f5cc50a5 WARN   Could not create Notifications-Tabletable Notifications already exists
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   Starting instance ts3server://prem.zhts3.us?port=4000&nickname=SinusBot&password=&channel=&channelpassword=
2018/07/06 17:23:06 X [MAIN] New connection
2018/07/06 17:23:06 X [MAIN] New connection
2018/07/06 17:23:06 X [MAIN] New connection
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |TeamSpeak 3 Client 3.1.9 (2018-05-04 13:54:44)
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |SystemInformation: Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 Binary: 64bit
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |Using hardware aes
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |ERROR   |SoundBckndIntf|   |libpulse.so.0: cannot open shared object file: No such file or directory
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |Unable to create an Open GL context.
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |Addons        |   |Checking for addon updates...
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |Plugins       |   |Loading plugin: libsoundbot_plugin.so
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |Plugins       |   |Loading plugin: libclientquery_plugin_linux_amd64.so
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |Query         |   |listening on 127.0.0.1:25639
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |successfully downloaded revocation list
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |*** Time [MAINWINDOW]: 177
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |*** Time [INIT]: 177
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |DEVELOP |ClientUI      |   |Notifications init: Soundpack path: /sinusbot/TeamSpeak3-Client-linux_amd64/sound/nosounds
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |Failed to init text to speech engine
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |Qt version: 5.6.1
2018/07/06 17:23:06 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |Using configuration location: /sinusbot/data/ts3/903988b8-0cfe-4bf7-9818-a6961ee47d14/f5cc50a5-d179-4add-8cff-e30860b6a6fa/settings.db
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |ts3server: prem.zhts3.us?port=4000&nickname=SinusBot&password=&channel=&channelpassword=
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Connect to server: prem.zhts3.us
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Trying to resolve prem.zhts3.us
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |SRV DNS resolve unsuccessful, "_ts3._udp.prem.zhts3.us" Domain name not found
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |A/AAAA DNS resolve successful, "prem.zhts3.us" =(h: 80.211.35.177 p:0)
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |A/AAAA DNS resolve for possible TSDNS successful, "prem.zhts3.us" =(h: 80.211.35.177 p:0)
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |A/AAAA DNS resolve for possible TSDNS successful, "zhts3.us" =(h: 192.64.119.62 p:0)
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |SRV DNS resolve unsuccessful, "_tsdns._tcp.zhts3.us" Domain name not found
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |Bookmarks     |   |Collecting autoconnect bookmarks
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |   |Last update check was: Tue Jan 1 00:00:01 2019
2018/07/06 17:23:07 903988b8 f5cc50a5 INFO   TS |INFO    |              |   |Statistics report: Not yet, next report on Wed Aug 1 17:17:52 2018
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |TSDNS queried unsuccessfully 80.211.35.177:41144
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |No TSDNS found
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |TSDNS queried unsuccessfully 192.64.119.62:41144
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |TSDNS         |   |No TSDNS found
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Lookup finished: ip=80.211.35.177 port=4000 query=prem.zhts3.us error=0
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Resolve successful: 80.211.35.177:4000
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Initiating connection: 80.211.35.177:4000
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |PreProSpeex   |1  |Speex version: 1.2rc1
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Connect status: Connecting
2018/07/06 17:23:09 903988b8 f5cc50a5 INFO   New connection status 1; Error 0
2018/07/06 17:23:14 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Connect status: Disconnected
2018/07/06 17:23:14 903988b8 f5cc50a5 INFO   TS |INFO    |ClientUI      |1  |Failed to connect to server, want autoreconnect = 0
2018/07/06 17:23:14 903988b8 f5cc50a5 INFO   The bot could not connect. This might have several reasons: the server doesn't exist at that address, the server password is wrong, the default channel doesn't exist, the bot has been banned, the server is an illegal installation or the password is wrong , the security level of your identity is too low or the server does not allow the version of the client you are using. See our Wiki / Forums for more help.
2018/07/06 17:23:14 903988b8 f5cc50a5 INFO   New connection status 0; Error 1797
2018/07/06 17:23:15 903988b8 f5cc50a5 INFO   TSClient quit.```

**Comment by calvinthefreak** [comment] 2018-09-21 11:09
the Issue still consists,
Server Version 3.4.0
and the Bots TS3 Version is 3.2.1 (Docker Pull latest)

```
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |              |   |TeamSpeak 3 Client 3.2.1 (2018-08-14 14:00:36)
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |              |   |SystemInformation: Linux 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 Binary: 64bit
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |              |   |Using hardware aes
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |ERROR   |SoundBckndIntf|   |libpulse.so.0: cannot open shared object file: No such file or directory
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |Unable to create an Open GL context.
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |ERROR   |RevocationListCache|   |Failed to import revocation list from cache
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |              |   |*** Time [ICONMANGER]: 149
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |Addons        |   |Checking for addon updates...
2018/09/21 11:05:49 114eda11 d55fef39 INFO   TS |INFO    |Plugins       |   |Loading plugin: libsoundbot_plugin.so
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |Plugins       |   |Loading plugin: libclientquery_plugin_linux_amd64.so
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |successfully downloaded revocation list for accounting
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |successfully downloaded revocation list for myteamspeak id
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |Query         |   |listening on 127.0.0.1:25639
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |*** Time [MAINWINDOW]: 489
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |*** Time [INIT]: 490
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |DEVELOP |ClientUI      |   |Notifications init: Soundpack path: /opt/sinusbot/TeamSpeak3-Client-linux_amd64/sound/nosounds
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |Failed to init text to speech engine
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |Qt version: 5.6.1
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |Using configuration location: /opt/sinusbot/data/ts3/114eda11-4f90-4e2c-8cd1-ecf46a759495/d55fef39-90cf-49d9-a1e9-45500ca9e37f/settings.db
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |ts3server: 127.0.0.1?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |1  |Connect to server: 127.0.0.1
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |1  |Initiating connection: 127.0.0.1:9987
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |PreProSpeex   |1  |Speex version: 1.2rc1
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |1  |Connect status: Connecting
2018/09/21 11:05:50 114eda11 d55fef39 INFO   New connection status 1; Error 0
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |Bookmarks     |   |Collecting autoconnect bookmarks
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |   |Last update check was: Tue Jan 1 00:00:01 2019
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |Statistics report: First run, report later in 1-30 days
2018/09/21 11:05:50 114eda11 d55fef39 INFO   TS |INFO    |              |   |Statistics report: Setting next report date to: Thu Oct 18 11:05:50 2018
2018/09/21 11:05:55 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |1  |Connect status: Disconnected
2018/09/21 11:05:55 114eda11 d55fef39 INFO   TS |INFO    |ClientUI      |1  |Failed to connect to server, want autoreconnect = 0
2018/09/21 11:05:55 114eda11 d55fef39 INFO   The bot could not connect. This might have several reasons: the server doesn't exist at that address, the server password is wrong, the default channel doesn't exist, the bot has been banned, the server is an illegal installation or the password is wrong , the security level of your identity is too low or the server does not allow the version of the client you are using. See our Wiki / Forums for more help.
2018/09/21 11:05:55 114eda11 d55fef39 INFO   New connection status 0; Error 1797
2018/09/21 11:05:56 114eda11 d55fef39 INFO   TSClient quit.
```



I did allready reinstall the Server and the Bot... 
Still not working... allways error 1797...


But other Servers than the local one are working.

**Comment by galexrt** [comment] 2018-09-23 07:42
@calvinc64 You can't connect to localhost of the host from inside the container.. You need to use the public IP or if the TeamSpeak server is running inside a container the container IP and/or using the DNS name of the TeamSpeak server container (e.g., see `/etc/hosts`).

**Comment by calvinthefreak** [comment] 2018-10-11 16:18
No Sorry, this is also not possible, when I try to connect to the server
via the external IPv4 Address.
OS: Ubuntu 16.04
