### ISSUE TITLE
Youtube-DL is not updating to latest version

### ISSUE THREAD

**Issue by rpa3ck** [galexrt/docker-sinusbot#44] opened 2018-09-09 11:46 UTC
Hi,
There was an issue with Youtube-DL couple of days ago where songs couldn't be played back via Youtube-DL. An update was released, but when I run the command to update the image:
`docker pull quay.io/galexrt/sinusbot:latest`
it says it's already up to date, but I'm pretty sure it is an outdated version, since I still can't play back any songs.. Is there any way to manually update it?

**Comment by galexrt** [comment] 2018-09-09 11:56
@rpa3ck The Docker images has been updated. You should be able to get the latest image by `docker pull` now.

**Comment by rpa3ck** [comment] 2018-09-09 12:27
Thanks for the quick response. I pulled in the updated images, but Youtube-DL is still showing old version.
`root@ns360750:~# docker exec -u root sinusbot-inst-2 youtube-dl --version`
`2018.08.04`

**Comment by galexrt** [comment] 2018-09-09 12:40
```
$ docker pull quay.io/galexrt/sinusbot:latest
latest: Pulling from galexrt/sinusbot
3b37166ec614: Already exists 
504facff238f: Already exists 
ebbcacd28e10: Already exists 
c7fb3351ecad: Already exists 
2e3debadcbf7: Already exists 
a885787ab15f: Already exists 
311a86f079a6: Already exists 
614ebe4231b5: Already exists 
Digest: sha256:4e190f22cb22fdefa6a4202df35e2be18e632c01355fd104467406042fe6b6fb
Status: Image is up to date for quay.io/galexrt/sinusbot:latest
$ docker run -it --entrypoint=/bin/bash quay.io/galexrt/sinusbot:latest
sinusbot@e24e2baf6a16:~$ youtube-dl -U
youtube-dl is up-to-date (2018.09.08)
sinusbot@e24e2baf6a16:~$
```

I'm unable to reproduce. Do you have an image cache?

**Comment by rpa3ck** [comment] 2018-09-09 12:54
When I check the Youtube-DL version in the image, it shows it is up to date. I might be missing a step during update? Here is what I did to update my docker instance (following the "Update" instructions on the page):

```
root@ns360750:~# docker pull quay.io/galexrt/sinusbot:latest
latest: Pulling from galexrt/sinusbot
3b37166ec614: Already exists
504facff238f: Already exists
ebbcacd28e10: Already exists
c7fb3351ecad: Already exists
2e3debadcbf7: Already exists
a885787ab15f: Already exists
311a86f079a6: Already exists
614ebe4231b5: Already exists
Digest: sha256:4e190f22cb22fdefa6a4202df35e2be18e632c01355fd104467406042fe6b6fb
Status: Image is up to date for quay.io/galexrt/sinusbot:latest
root@ns360750:~# docker restart sinusbot-inst-2
sinusbot-inst-2
root@ns360750:~# docker exec -u root sinusbot-inst-2 youtube-dl --version
2018.08.04
```

**Comment by galexrt** [comment] 2018-09-09 14:25
@rpa3ck You need to delete the existing container and create it again.

Let me know if that works for your setup.

**Comment by galexrt** [comment] 2018-09-09 14:32
Closing as the image and with that youtube-dl, has been updated.

**Closed as completed by galexrt** 2018-09-09 14:32 UTC

**Comment by peralta00** [comment] 2018-11-08 16:28
Its not updating again :/
I already updated the image and rebuilded all sinusbot containers.

**Comment by galexrt** [comment] 2018-11-08 19:12
@peralta00 "rebuilded all sinusbot containers"? Do you mean stopped, deleted and run the container again?

**Comment by peralta00** [comment] 2018-11-09 00:25
@galexrt yes, stop -> delete -> create a new one.

**Comment by galexrt** [comment] 2018-11-10 18:13
@peralta00 Images have been updated, pull the images again and recreate the containers.

You can also try running `docker exec -u root:root -it CONTAINER_NAME youtube-dl -U` per container.
