### ISSUE TITLE
After the new Update from 06.08.2017 the Bot cannot start

### ISSUE THREAD

**Issue by Jormodn** [galexrt/docker-sinusbot#22] opened 2017-08-08 17:46 UTC
I removed the Image and delete all data from mounts.

I reinstalled the Image and the log show this:

-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
-> Copying original sinusbot scripts to volume ...
=> Sinusbot scripts copied.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Updating to version 2017.08.06 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
This version has expired. Please download a newer version from the official SinusBot website and upgrade.

The newest Version is running but the Sinusbot say that is outdated.

**Comment by galexrt** [comment] 2017-08-09 06:31
A fix is on it's way.

**Comment by galexrt** [comment] 2017-08-09 06:41
What's the name of the Docker image you are using?

***

Please repull the image `docker pull quay.io/galexrt/sinusbot:latest`. A fix should have been implemented now.

**Comment by fa-dx** [comment] 2017-09-03 18:13
This appears to be an issue again:

=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
youtube-dl is up-to-date (2017.09.02)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
This version has expired. Please download a newer version from the official SinusBot website and upgrade.

**Comment by galexrt** [comment] 2017-09-03 18:15
@fa-dx Run `docker pull galexrt/sinusbot:latest` and/or `docker pull quay.io/galexrt/sinusbot:latest`. The commands pull the latest image. You need to restart your containers after that.

**Comment by fa-dx** [comment] 2017-09-03 18:24
It appears my server is having trouble connecting to sinusbots update server, not an issue with this. Thanks anyway!

**Comment by galexrt** [comment] 2017-09-04 06:38
Closing this issue, as I can't reproduce with the latest build.

**NOTE**: If you experience this issue, please repull the image and try again before opening an issue about it.

**Closed as completed by galexrt** 2017-09-04 06:38 UTC
Labels: bug

**Comment by MrWitold** [comment] 2017-10-04 13:24
I'm not sure but i think that this error appears again.

```
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
-> Copying original sinusbot scripts to volume ...
=> Sinusbot scripts copied.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.10.01)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
This version has expired. Please download a newer version from the official SinusBot website and upgrade.
```

**Comment by galexrt** [comment] 2017-10-04 16:38
@MrWitold Which docker image are you using? `galexrt/sinusbot:latest` or `quay.io/galexrt/sinusbot:latest`?

Please try using the latest docker images version from Docker Hub: `docker pull galexrt/sinusbot:latest` and not the image from `quay.io`.

**Comment by MrWitold** [comment] 2017-10-04 19:19
Okay, now It works but I have no idea why the version of the Sinusbot is ~0.10.6

```
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
-> Copying original sinusbot scripts to volume ...
=> Sinusbot scripts copied.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.10.01)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
2017/10/04 19:14:52 X [MAIN] Starting up fake x-server...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.10.6-6b6bd3a
(C) 2013-2017 Michael Friese. All rights reserved.

2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2017/10/04 19:14:52 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
```

**Comment by galexrt** [comment] 2017-10-04 21:07
@MrWitold The image uses the latest beta build/download url from sinusbot. The `0.10.x` seems to be the most recent version uploaded to `sinusbot.com` beta release.

**Comment by MrWitold** [comment] 2017-10-04 21:20
Ohh..I'm so sorry for disrupting. I got in mind that the newest update is around 9.20 but it looks like today was update to 0.10.x, also I got in mind that the version 0.10.x is older then 9.20. One more time I want to sorry for this stupid question and say thanks for help.

**Comment by galexrt** [comment] 2017-10-04 21:22
@MrWitold No problem! If there is anything else I can help you with, please let me know.
