### ISSUE TITLE
Something wrong with bot and youtube-dl

### ISSUE THREAD

**Issue by Vampire212** [galexrt/docker-sinusbot#40] opened 2018-08-18 22:09 UTC
My bot was working well but after some time, youtube download stopped working  and I restarted bot many times but it keeps repeating this :- 

 => Starting SinusBot (https://sinusbot.com) by Michael Friese ...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.11.0-8e5f1a2
(C) 2013-2017 Michael Friese. All rights reserved.

2018/05/23 14:00:54 X [MAIN] Starting up fake x-server...
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin Youtube_Search.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2018/05/23 14:00:54 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
could not contact update server
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
ERROR: can't find the current version. Please try again later.
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.11.0-8e5f1a2
(C) 2013-2017 Michael Friese. All rights reserved.

2018/05/23 14:01:47 X [MAIN] Starting up fake x-server...
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin Youtube_Search.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2018/05/23 14:01:47 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
could not contact update server
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
ERROR: can't find the current version. Please try again later.
=> Updated youtube-dl with exit code 0

**Comment by galexrt** [comment] 2018-08-19 11:18
@Vampire212 Are you on the latest version of the image? `docker pull SINUSBOT_IMAGE_USED` and restart to update the image.

**Comment by galexrt** [comment] 2018-08-19 21:45
I'm unable to reproduce the error. Closing until @Vampire212 replied if the latest image "fixes" the issue he is experiencing.

**Closed as completed by galexrt** 2018-08-19 21:45 UTC
