### ISSUE TITLE
cannot allocate memory and download failed for https/www.youtube.com/watch?v=***; youtube-dl download failed (check youtube-dl)

### ISSUE THREAD

**Issue by MrWitold** [galexrt/docker-sinusbot#21] opened 2017-07-13 00:28 UTC
Hi,

I got 2 issues, one of them is that, when I create new image or just turn off the bot, all works okay(website and settings works) to time when I click the button to connect the bot to the server then I see this message in "Instance Log"

```
2017-07-13T02:13:29+02:00 Closed.

2017-07-13T02:13:29+02:00 TSClient quit. LogLevel has been increased, please try to connect again to see more details.

2017-07-13T02:13:29+02:00 Error spawning instancefork/exec /sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: cannot allocate memory

2017-07-13T02:13:29+02:00 Starting instance ts3server://147.135.209.143?port=1337&nickname=%E2%99%AA%20Bot%20Muzyczny%20%23%20Poczekalnia%20%E2%99%AA&password=&channel=&channelpassword=

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not insert into FileTransfer-Tableno such table: FileTransfer

2017-07-13T02:13:29+02:00 Could not delete from FileTransferno such table: FileTransfer


2017-07-13T02:13:29+02:00 Could not create Notifications-Tabletable Notifications already exists

2017-07-13T02:13:29+02:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists

2017-07-13T02:13:29+02:00 Could not create Chat-Tabletable Chat already exists

2017-07-13T02:13:29+02:00 About to run.
```

Sometimes to solve that, I had to restart whole machine but It isn't works always.
Yes, I have enought memory - (0.3/1.9 GB) - in time when it happens.

And second issues is that the youtube-dl don't works. After reboot it works for 1 minute and then I see this error

```
Download failed for https/www.youtube.com/watch?v=***; youtube-dl download failed (check youtube-dl)
```

Updating, rebooting - doesn't help.

**Comment by galexrt** [comment] 2017-07-13 08:33
To help you with your issue the following information is needed from you:
* What OS are you using?
* What Docker image tag are you using?
* Kernel version?

**Comment by MrWitold** [comment] 2017-07-13 12:07
- Ubuntu 16.10

- By the Docker image you mean that "galexrt/sinusbot:latest" ?

- 4.4.0-81-generic

**Comment by galexrt** [comment] 2017-07-13 21:14
I'm looking into it.

**Comment by MrWitold** [comment] 2017-07-13 22:35
Okay, just for information I wanna say that I was looking for answer but I just find information on sinusbot forum to solved that i have to run the process as administrator but It was for windows OS and not for docker solution.

**Comment by galexrt** [comment] 2017-07-14 11:50
Please repull the Docker image as I'm not able to reproduce this issue.
If you still experience this issue, move your data directory and try with a new data directory/volume.

**Comment by RealRunSpace** [comment] 2017-09-18 10:35
I'm still having that issue, I've tryed to repull it and nothing

**Comment by RealRunSpace** [comment] 2017-09-18 10:36
also, same settings as MrWitold

**Comment by MrWitold** [comment] 2017-09-18 11:45
What hosting are you using?

**Comment by RealRunSpace** [comment] 2017-09-18 11:54
Vultr, but now I'll try on OVH, same Ubuntu 16.04

**Comment by RealRunSpace** [comment] 2017-09-18 12:01
nah, same problem on OVH, I have avaliable ram and storage

**Comment by RealRunSpace** [comment] 2017-09-18 12:26
```
              total        used        free      shared  buff/cache   available
Mem:           992M         77M        531M        2.7M        383M        738M
Swap:          951M         36M        915M
```

**Comment by RealRunSpace** [comment] 2017-09-18 12:41
well, I have followed this guide to install the original sinusbot (https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu)
So it must be something about the docker, I think you need to downgrade the TS3 version to this one:
Download provided by SinusBot: http://dl.4players.de/ts/releases/3.0.18.2/TeamSpeak3-Client-linux_amd64-3.0.18.2.run
Version: 3.0.18.2

**Comment by galexrt** [comment] 2017-09-18 12:45
What command do you use to run the sinusbot container?

**Comment by RealRunSpace** [comment] 2017-09-18 12:53
`docker run --restart=always --name sinusbot8087 -d -v /opt/sinusbot/sinusbot8087:/sinusbot/data:z -p 8087:8087 quay.io/galexrt/sinusbot:latest`

**Comment by galexrt** [comment] 2017-09-18 12:55
@RealRunSpace Have you already tried moving your current data directory so a new is created? I don't get this issue on any of my test environments.

**Comment by RealRunSpace** [comment] 2017-09-18 12:56
I deleted it and still happening, do I try to a different one?

**Comment by galexrt** [comment] 2017-09-18 12:58
The latest docker image on a `4.12.11` kernel with:
```
              total        used        free      shared  buff/cache   available
Mem:            15G        4,8G        4,5G        1,2G        6,3G        9,3G
```
works for me.
Can you try on a server with more than 0.5GB of RAM?

**Comment by RealRunSpace** [comment] 2017-09-18 13:01
I've tried on OVH which have 2GBRam and same thing happens

**Comment by RealRunSpace** [comment] 2017-09-18 13:07
I will try to purchase a new VPS and clean with 1GB, so it will be dedicated to sinusbot and it's docker

**Comment by RealRunSpace** [comment] 2017-09-18 13:25
This are the stats of the OVH machine with 2GB
```
              total        used        free      shared  buff/cache   available
Mem:           1952          88         945          20         918        1638
Swap:             0           0           0
```

**Comment by RealRunSpace** [comment] 2017-09-18 13:44
Oh, also "uname -r" from the 2GB OVH machine
`4.4.0-81-generic`

**Comment by galexrt** [comment] 2017-09-18 14:14
@RealRunSpace Did it work on the 1GB and/or 2GB machine?

**Comment by RealRunSpace** [comment] 2017-09-18 14:25
nope, same error

**Comment by RealRunSpace** [comment] 2017-09-18 15:25
Try to update the script to the official one, to a lower version of TS, I think that's the problem on some VPS

**Comment by RealRunSpace** [comment] 2017-09-18 15:25
This >>

(https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu)
So it must be something about the docker, I think you need to downgrade the TS3 version to this one:
Download provided by SinusBot: http://dl.4players.de/ts/releases/3.0.18.2/TeamSpeak3-Client-linux_amd64-3.0.18.2.run
Version: 3.0.18.2

**Comment by galexrt** [comment] 2017-09-18 15:37
@RealRunSpace It's working for me, but if you want you can create a pull request to change the TS3 version to `3.0.18.2`.

**Comment by RealRunSpace** [comment] 2017-09-18 17:10
submited

**Comment by galexrt** [comment] 2017-09-18 18:32
@RealRunSpace You opened the pull request in the wrong repository. You have to point the pull request to `galexrt/docker-sinusbot`.

**Comment by RealRunSpace** [comment] 2017-09-18 18:55
when I click submit pull request I go there

**Comment by RealRunSpace** [comment] 2017-09-18 20:30
nah this is really a bug on some ubuntu, 1.7GB RAM avaliable and still popping this
```
2017-09-18T22:28:55+02:00 Closed.
2017-09-18T22:28:55+02:00 TSClient quit. LogLevel has been increased, please try to connect again to see more details.
2017-09-18T22:28:55+02:00 Error spawning instancefork/exec /sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: cannot allocate memory
2017-09-18T22:28:55+02:00 Starting instance ts3server://127.0.0.1?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
2017-09-18T22:28:42+02:00 TSClient quit.
2017-09-18T22:28:41+02:00 New connection status 0; Error 0
2017-09-18T22:28:41+02:00 The bot could not connect. This might have several reasons: the server doesn't exist at that address, the server password is wrong, the default channel doesn't exist, the bot has been banned, the server is an illegal installation or the password is wrong , the security level of your identity is too low or the server does not allow the version of the client you are using. See our Wiki / Forums for more help.
```

**Comment by galexrt** [comment] 2017-09-18 20:53
Did you only try ubuntu on all servers you have tested on?

**Comment by RealRunSpace** [comment] 2017-09-18 20:54
Yes, and I'm thinking to try on Debian, it should be equal or very similar

**Comment by galexrt** [comment] 2017-09-18 20:56
@RealRunSpace Yes they are very similar. But just to see if it is an issue for Ubuntu.

**Comment by RealRunSpace** [comment] 2017-09-18 21:00
Tomorrow I'll try on inter server paying 0.01$ for Debian, if it works later I will purchase a new one in Aruba (as its 1$/month and inter is 5$/month except the first one)

**Comment by RealRunSpace** [comment] 2017-09-19 10:11
Now i'm purchasing the VPS, if it doesn't work on debian I will make the last attemp on ubuntu 16.04 on a 32GB DEDICATED server on 1&1 and I will tell you how is going

**Comment by RealRunSpace** [comment] 2017-09-19 10:31
Ok, is not your bug, it's an UBUNTU bug, it loaded in debian correctly, no problems (apparently), I will test some more instances and I'll comment the result, thanks @galexrt for you great great HELP!!!

**Comment by RealRunSpace** [comment] 2017-09-19 10:31
also, one question, how many bots can hold until you get blacklisted or something?

**Comment by galexrt** [comment] 2017-09-19 10:53
@RealRunSpace You are only allowed to run as many bots as the license of sinusbot, you hold, allows you to run.
If you run more you go against the Sinusbot license and can be held accountable for the license violation(s).

**Comment by RealRunSpace** [comment] 2017-09-19 17:50
Ok, I got a new error, opening issue...

**Comment by RealRunSpace** [comment] 2017-09-19 17:50
sorry! nothing!! (last comment was deleted)

**Comment by galexrt** [comment] 2017-09-19 20:40
I'm going to close this issue for now.
But will make the change to the lower TeamSpeak the next few days to ship around the Ubuntu issue.

**Closed as completed by galexrt** 2017-09-19 20:40 UTC
Labels: wontfix

**Comment by galexrt** [comment] 2017-09-20 08:42
I just pushed the teamspeak version change myself. Image should be updated in about 5-10 minutes. Please repull the image.

As I already wrote, please close the PR in the `VeltroGaming` repository. `VeltroGaming` is not the right repository for the PR.

**Comment by galexrt** [comment] 2017-09-20 21:16
@RealRunSpace Can you please test if the new image works on Ubuntu now with Teamspeak `3.0.18.2`?

**Comment by RealRunSpace** [comment] 2017-09-21 09:00
Nope,
```
2017-09-21T10:59:43+02:00 Closed.
2017-09-21T10:59:43+02:00 TSClient quit. LogLevel has been increased, please try to connect again to see more details.
2017-09-21T10:59:43+02:00 Error spawning instancefork/exec /sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: cannot allocate memory
```

**Comment by galexrt** [comment] 2017-09-21 09:01
You repulled the image, right?

**Comment by RealRunSpace** [comment] 2017-09-22 08:48
Yep

**Comment by galexrt** [comment] 2017-09-25 07:22
> This >>
>
> (https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu)
> So it must be something about the docker, I think you need to downgrade the TS3 version to this one:
> Download provided by SinusBot: http://dl.4players.de/ts/releases/3.0.18.2/TeamSpeak3-Client-linux_amd64-3.0.18.2.run
> Version: 3.0.18.2

@RealRunSpace Your "fix" changing the TS3 version didn't work then.
I suggest you raise an error in the TeamSpeak forums about the `2017-09-21T10:59:43+02:00 Error spawning instancefork/exec /sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: cannot allocate memory` error.

BTW How did you repull the image?

**Comment by RealRunSpace** [comment] 2017-09-26 15:48
with docker pull

**Comment by galexrt** [comment] 2017-09-30 14:04
@RealRunSpace Is a normal installation of teamspeak client working on an ubuntu server?

It really seems to be an issue with the TeamSpeak client.

BTW I finally have got the time to test it on an Ubuntu server. I can confirm that this is an issue on Ubuntu with the docker image. Haven't tested with TeamSpeak client directly installed.

**Comment by hub2** [comment] 2017-12-09 15:21
Is there any progress on the issue?

**Comment by galexrt** [comment] 2017-12-09 15:31
@hub2 Did you also experience this issue on Ubuntu?

**Comment by hub2** [comment] 2017-12-09 15:34
Yes, 
`Ubuntu x86_64 4.4.0-64-generic`
VPS with 1.7GB free RAM

Web interface works but sinusbot won't start with this error:
`Error spawning instancefork/exec /sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: cannot allocate memory`

**Comment by galexrt** [comment] 2017-12-09 16:22
The error actually means that TeamSpeak isn't working. Could you try installing different TeamSpeak versions directly on to the server and check if they work (you would just need to run the `ts3client_linux_amd64` binary to test it)

**Comment by galexrt** [comment] 2017-12-17 13:10
@hub2 Dd you try what I suggested you? As I wrote it could be the TeamSpeak version. But I'm currently not running Ubuntu.

**Comment by hub2** [comment] 2017-12-17 13:14
I installed sinusbot without docker, with teamspeak version suggested in the sinusbot guide (https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu), that is 3.0.18.2, it works fine for few days now.

**Comment by hub2** [comment] 2017-12-17 13:19
I suggest you use the same version in your docker if that's the one recommended by sinusbot authors to avoid any problems(after all, version doesn't matter as long as sinusbot can do all it needs to do)

**Comment by galexrt** [comment] 2017-12-17 13:52
@hub2 @RealRunSpace I switched the image back to use TS3 version `3.0.18.2` could you please try with the new image.
Run `docker pull quay.io/galexrt/sinusbot:latest` or if you use the Docker Hub image `docker pull galexrt/sinusbot:latest` and then delete the current Sinusbot container and start it again.
