### ISSUE TITLE
All containers suddenly restarting

### ISSUE THREAD

**Issue by RealRunSpace** [galexrt/docker-sinusbot#48] opened 2019-05-30 19:51 UTC
All containers suddenly started to restart in a loop with this message:

**2019-05-30T19:14:14.868367264Z could not contact update server**

**Comment by Horstexplorer** [comment] 2019-05-30 20:12
Hi,
the "could not contact update server" error can be caused by various reasons.
Mostly it is caused by a wrong system time so you may want to check that, but as you wrote "All containers", which I think of as "multiple sinusbot docker", the IP of your host may be blocked due to license violation. In this case you should contact the sinusbot staff to fix this.
You may aswell want to remove the restart-always flag of your container to break such restart loops (or manually stop the docker)

**Comment by RealRunSpace** [comment] 2019-05-30 20:20
Ok thanks, the bots was working fine for lot of time so it was strange, thanks

**Comment by galexrt** [comment] 2019-05-30 21:29
Closing this issue as the problem described seems to be caused by violation of Sinusbot's license.

Please follow the Sinusbot license and only run the amount of instances that you are allowed to run, this project is not meant for going against the license! This project is merely a way to easily run the amount of instances that you are allowed to run by the license you have acquired from Sinusbot.

See https://wiki.sinusbot.com/en:info:licenses.

**Closed as completed** 2019-05-30 21:29 UTC
