### ISSUE TITLE
Youtube-dl slow fix

### ISSUE THREAD

**Issue by Vampire212** [galexrt/docker-sinusbot#29] opened 2018-01-29 03:45 UTC
Youtube-dl is very slow (it's speed <200 kbps), the problem that when youtube-dl downloads by youtube-dl -x (audio files) from youtube it downloads at slow speed, So there a temporary solution which is to update the image and do this: change config.ini to point at the new file youtube-dl2.
`YoutubeDLPath2 = "/usr/local/bin/youtube-dl"`
`YoutubeDLPath = "./youtube-dl2"`
Create the file youtube-dl2 in the same folder, then edit it and type this :

> #!/bin/bash
youtube-dl ${@/bestaudio/43}

and use 
 `chmod +x youtube-dl2`
to make it executable.
That file replaces the -f bestaudio flag for the download to -f 43. Format 43 seems to be the .webm format which is not throttled by youtube.
That temporary solution was submitted by TomRiddle01 here: https://forum.sinusbot.com/threads/not-a-bug-youtube-dl-slow-download-rate.4679/page-2
I hope it helps.

**Comment by galexrt** [comment] 2018-01-29 19:21
This should be resolved by the latest changes. New image should be built in 15 minutes.
Repull the image and restart your Sinusbot containers.
Let me know if that fixes the issue.

**Closed as completed** 2018-01-29 19:21 UTC

**Comment by Vampire212** [comment] 2018-01-29 21:49
youtube-dl is missing now..

**Comment by galexrt** [comment] 2018-01-30 14:22
@Vampire212 This should be solved now. Please repull the image and check again.

**Comment by Vampire212** [comment] 2018-01-30 18:06
Thanks. It works now.

**Comment by ambreenmoeen** [comment] 2018-07-03 00:37
If you still facing the youtube slow problem then [https://windowserrors.org/fix-youtube-slow-loading-problem/](https://windowserrors.org/fix-youtube-slow-loading-problem/) is the recommended source to resolve it.

**Comment by galexrt** [comment] 2018-07-03 06:01
@ambreenmoeen The problem is not that Youtube is slow in the regard of "pure" viewing..
`youtube-dl` by default through Sinusbot pulls the highest quality. Youtube has now "restrictions" for downloading certain formats (e.g. highest quality mp3) in place causing the `youtube-dl` download speed to be low when not using a "hack" for youtube-dl which simply replaces the `bestaudio` through a "lower" quality format, see https://github.com/galexrt/docker-sinusbot/blob/master/youtube-dl-speedpatched#L3.
